# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "lucid32"

  config.vm.customize do |vm|
    vm.memory_size = 256
    vm.name = "dev.gitorama.com"
  end

  config.vm.network :hostonly, "192.168.100.2"

  config.vm.forward_port 8000, 8000
  config.vm.forward_port 27017, 27017
end
